### ISSUE TITLE
[optimization] Do `==` condition first in if-else statements to save 1 operation

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/jokerace-eligibility#10]
flip the order of the conditions here

https://github.com/Hats-Protocol/jokerace-eligibility/blob/f7dc50a8988ac487172ea330ca4250c0a65f84e4/src/JokeraceEligibility.sol#L175

eg 

```
 if (admin == address(0)) {
            if (!HATS().isAdminOfHat(msg.sender, hatId())) {
                revert JokeraceEligibility_NotAdmin();
            }
            
        } else {
            if (msg.sender != admin) {
                revert JokeraceEligibility_NotAdmin();
            }
        }
```

**Comment by gershido** [comment]
fixed in #11:
https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#L165-L175
