### ISSUE TITLE
[optimization] read underlyingContest earlier

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/jokerace-eligibility#3]
Read `currentContest` into memory before this line so that you only have to read it once in this call

https://github.com/Hats-Protocol/jokerace-eligibility/blob/f7dc50a8988ac487172ea330ca4250c0a65f84e4/src/JokeraceEligibility.sol#L128

**Comment by gershido** [comment]
fixed in #11:
https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#L124-L129

**Comment by spengrah** [comment]
you can also use currentContest on line 132
