### ISSUE TITLE
Admin as a hat

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/jokerace-eligibility#5]
I suggest setting the contract owner as a hatId instead of an address. That gives the DAO flexibility to choose which role can set initiate re-elections. And we can still do the same fallback to the election hat's admin if left empty.

**Comment by spengrah** [comment]
the other nice thing is that since a hat can be transferred to a new wearer, we can skip updating the admin in `reelection`, which then allows us to set the admin hat as an immutable arg and save some gas

**Comment by gershido** [comment]
fixed in #11:
https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#L59-L63
