### ISSUE TITLE
[optimization] re-use numProposals

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/jokerace-eligibility#6]
Can use `numProposals` on this line

https://github.com/Hats-Protocol/jokerace-eligibility/blob/f7dc50a8988ac487172ea330ca4250c0a65f84e4/src/JokeraceEligibility.sol#L138

**Comment by gershido** [comment]
fixed in #11:
https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#LL137C14-L137C14
