### ISSUE TITLE
[optimization] handle `numEligibleWearers = topK < numProposals` inside existing if block

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/jokerace-eligibility#7]
The conditional on lines 138 and 154 are the same, so you can get rid of one of them by setting `numEligibleWearers` as a result of the first.

**Comment by gershido** [comment]
fixed in #11:
https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#L134-L147

**Comment by spengrah** [comment]
I would also move the assignment on line 134 to an else statement after the if-block.
