### ISSUE TITLE
solidity mappings can take names 🔥

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/jokerace-eligibility#8]
[As of solc 0.8.18](https://docs.soliditylang.org/en/v0.8.18/types.html#mapping-types), mappings now take optional key and value names! So we no longer have to use a comment to clarify.

**Comment by gershido** [comment]
fixed in #11:
https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#L75-L76
