### ISSUE TITLE
do total votes math inside `getVotes()`

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/jokerace-eligibility#9]
that way you won't have to write the same logic twice for K and K+1 proposals. https://github.com/Hats-Protocol/jokerace-eligibility/blob/f7dc50a8988ac487172ea330ca4250c0a65f84e4/src/JokeraceEligibility.sol#L205

**Comment by gershido** [comment]
fixed in #11:
https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#L196-L199

**Comment by spengrah** [comment]
I wonder what we should do in the case that a given topK proposal has negative total votes? We could be opinionated and not mint them a hat. @gershido what do you think?

Advantages:
- probably the right approach from a governance perspective
- we wouldn't need to use signed int types

Drawbacks:
- we'd need to add that logic and skip minting for a given hat

**Comment by gershido** [comment]
Interesting point. It won't fit use cases in which the elections are to choose the top k least hated candidates :) 
It made me think in general that we'll probably find many configurations that make sense per different use-cases. The question is how we'll handle them: one configurable module or a module per configuration (can be also something in the middle). I think I will prefer to leave this one as the most general / least opinionated, just as the first instance

**Comment by spengrah** [comment]
that works for me as a starting place, just be sure to document it clearly. 

We'll likely get some good guidance / signal when we share this with the Jokerace team and any DAOs interested in using jokerace for hat elections.
